using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Nexora.Domain.Scheduling;

namespace Nexora.Infrastructure.Persistence;

public sealed class WorkingHoursConfiguration:IEntityTypeConfiguration<WorkingHours>{public void Configure(EntityTypeBuilder<WorkingHours>b){b.ToTable("working_hours");b.HasKey(x=>x.Id);b.Property(x=>x.StartLocal).HasColumnType("time without time zone");b.Property(x=>x.EndLocal).HasColumnType("time without time zone");b.HasIndex(x=>new{x.TenantId,x.ProfessionalId,x.DayOfWeek}).IsUnique();b.HasOne<Nexora.Domain.Catalog.Professional>().WithMany().HasForeignKey(x=>new{x.TenantId,x.ProfessionalId}).HasPrincipalKey(x=>new{x.TenantId,x.Id}).OnDelete(DeleteBehavior.Cascade);}}
public sealed class BlockedPeriodConfiguration:IEntityTypeConfiguration<BlockedPeriod>{public void Configure(EntityTypeBuilder<BlockedPeriod>b){b.ToTable("blocked_periods");b.HasKey(x=>x.Id);b.Property(x=>x.StartAt).HasColumnType("timestamp with time zone");b.Property(x=>x.EndAt).HasColumnType("timestamp with time zone");b.Property(x=>x.Reason).HasMaxLength(500);b.HasIndex(x=>new{x.TenantId,x.ProfessionalId,x.StartAt});b.HasOne<Nexora.Domain.Catalog.Professional>().WithMany().HasForeignKey(x=>new{x.TenantId,x.ProfessionalId}).HasPrincipalKey(x=>new{x.TenantId,x.Id}).OnDelete(DeleteBehavior.Cascade);}}
public sealed class AppointmentConfiguration:IEntityTypeConfiguration<Appointment>{public void Configure(EntityTypeBuilder<Appointment>b){b.ToTable("appointments");b.HasKey(x=>x.Id);b.Property(x=>x.StartAt).HasColumnType("timestamp with time zone");b.Property(x=>x.EndAt).HasColumnType("timestamp with time zone");b.Property(x=>x.CreatedAt).HasColumnType("timestamp with time zone");b.Property(x=>x.UpdatedAt).HasColumnType("timestamp with time zone");b.Property(x=>x.Status).HasConversion<string>().HasMaxLength(30);b.Property(x=>x.Notes).HasMaxLength(4000);b.HasIndex(x=>new{x.TenantId,x.StartAt});b.HasIndex(x=>new{x.TenantId,x.ProfessionalId,x.StartAt});b.HasIndex(x=>new{x.TenantId,x.CustomerId});b.HasOne<Nexora.Domain.Customers.Customer>().WithMany().HasForeignKey(x=>new{x.TenantId,x.CustomerId}).HasPrincipalKey(x=>new{x.TenantId,x.Id}).OnDelete(DeleteBehavior.Restrict);b.HasOne<Nexora.Domain.Catalog.Professional>().WithMany().HasForeignKey(x=>new{x.TenantId,x.ProfessionalId}).HasPrincipalKey(x=>new{x.TenantId,x.Id}).OnDelete(DeleteBehavior.Restrict);b.HasOne<Nexora.Domain.Catalog.Service>().WithMany().HasForeignKey(x=>new{x.TenantId,x.ServiceId}).HasPrincipalKey(x=>new{x.TenantId,x.Id}).OnDelete(DeleteBehavior.Restrict);}}
