using Microsoft.EntityFrameworkCore;using Nexora.Application.Catalog;using Nexora.Application.Plans;using Nexora.Domain.Catalog;using Nexora.Infrastructure.Persistence;
namespace Nexora.Infrastructure.Catalog;
public sealed class CatalogService(NexoraDbContext db,IFeatureAccessService features):ICatalogService
{
 public async Task<IReadOnlyList<ProfessionalView>>GetProfessionalsAsync(Guid t,CancellationToken ct)=>(await db.Professionals.Where(x=>x.TenantId==t).Include(x=>x.Services).OrderBy(x=>x.Name).AsNoTracking().ToListAsync(ct)).Select(Map).ToList();public async Task<ProfessionalView?>GetProfessionalAsync(Guid t,Guid id,CancellationToken ct){var x=await db.Professionals.Where(x=>x.TenantId==t&&x.Id==id).Include(x=>x.Services).AsNoTracking().SingleOrDefaultAsync(ct);return x is null?null:Map(x);}public async Task<ProfessionalView>CreateProfessionalAsync(Guid t,ProfessionalInput i,CancellationToken ct){Validate(i);await EnforceProfessionalLimitAsync(t,ct);var x=new Professional(t,i.Name.Trim(),Clean(i.Email),Clean(i.Phone));db.Add(x);await db.SaveChangesAsync(ct);return Map(x);}
 private async Task EnforceProfessionalLimitAsync(Guid t,CancellationToken ct){var access=await features.ResolveAsync(t,FeatureCodes.Professionals,ct);if(access.Limit is not int max)return;var current=await db.Professionals.CountAsync(x=>x.TenantId==t&&x.IsActive,ct);if(current>=max)throw new PlanLimitExceededException(FeatureCodes.Professionals,max,current);}public async Task<ProfessionalView?>UpdateProfessionalAsync(Guid t,Guid id,ProfessionalInput i,CancellationToken ct){Validate(i);var x=await db.Professionals.Include(p=>p.Services).SingleOrDefaultAsync(x=>x.TenantId==t&&x.Id==id,ct);if(x is null)return null;x.Update(i.Name.Trim(),Clean(i.Email),Clean(i.Phone),i.IsActive);await db.SaveChangesAsync(ct);return Map(x);}public async Task<bool>DeleteProfessionalAsync(Guid t,Guid id,CancellationToken ct){var x=await db.Professionals.SingleOrDefaultAsync(x=>x.TenantId==t&&x.Id==id,ct);if(x is null)return false;db.Remove(x);await db.SaveChangesAsync(ct);return true;}
 public async Task<IReadOnlyList<ServiceView>>GetServicesAsync(Guid t,CancellationToken ct)=>(await db.Services.Where(x=>x.TenantId==t).OrderBy(x=>x.Name).AsNoTracking().ToListAsync(ct)).Select(Map).ToList();public async Task<ServiceView>CreateServiceAsync(Guid t,ServiceInput i,CancellationToken ct){Validate(i);var x=new Service(t,i.Name.Trim(),Clean(i.Description),i.DurationMinutes,i.Price);db.Add(x);await db.SaveChangesAsync(ct);return Map(x);}public async Task<ServiceView?>UpdateServiceAsync(Guid t,Guid id,ServiceInput i,CancellationToken ct){Validate(i);var x=await db.Services.SingleOrDefaultAsync(x=>x.TenantId==t&&x.Id==id,ct);if(x is null)return null;x.Update(i.Name.Trim(),Clean(i.Description),i.DurationMinutes,i.Price,i.IsActive);await db.SaveChangesAsync(ct);return Map(x);}public async Task<bool>DeleteServiceAsync(Guid t,Guid id,CancellationToken ct){var x=await db.Services.SingleOrDefaultAsync(x=>x.TenantId==t&&x.Id==id,ct);if(x is null)return false;db.Remove(x);await db.SaveChangesAsync(ct);return true;}
 public async Task<bool>LinkAsync(Guid t,Guid p,Guid s,CancellationToken ct){var professional=await db.Professionals.SingleOrDefaultAsync(x=>x.TenantId==t&&x.Id==p&&x.IsActive,ct);var service=await db.Services.SingleOrDefaultAsync(x=>x.TenantId==t&&x.Id==s&&x.IsActive,ct);if(professional is null||service is null)return false;if(!await db.ProfessionalServices.AnyAsync(x=>x.TenantId==t&&x.ProfessionalId==p&&x.ServiceId==s,ct)){db.Add(new ProfessionalService(t,p,s));await db.SaveChangesAsync(ct);}return true;}public async Task<bool>UnlinkAsync(Guid t,Guid p,Guid s,CancellationToken ct){var x=await db.ProfessionalServices.SingleOrDefaultAsync(x=>x.TenantId==t&&x.ProfessionalId==p&&x.ServiceId==s,ct);if(x is null)return false;db.Remove(x);await db.SaveChangesAsync(ct);return true;}
 private static void Validate(ProfessionalInput i){if(string.IsNullOrWhiteSpace(i.Name)||i.Name.Length>200||i.Email?.Length>320||i.Phone?.Length>40)throw new CatalogValidationException("Professional data is invalid.");}private static void Validate(ServiceInput i){if(string.IsNullOrWhiteSpace(i.Name)||i.Name.Length>200||i.DurationMinutes<=0||i.Price<0||i.Description?.Length>2000)throw new CatalogValidationException("Service data is invalid.");}private static string?Clean(string?v)=>string.IsNullOrWhiteSpace(v)?null:v.Trim();private static ProfessionalView Map(Professional x)=>new(x.Id,x.Name,x.Email,x.Phone,x.IsActive,x.Services.Select(s=>s.ServiceId).ToList());private static ServiceView Map(Service x)=>new(x.Id,x.Name,x.Description,x.DurationMinutes,x.Price,x.IsActive);
}
