using Microsoft.EntityFrameworkCore;
using Nexora.Application.Administration;
using Nexora.Application.Plans;
using Nexora.Domain.Plans;
using Nexora.Infrastructure.Persistence;

namespace Nexora.Infrastructure.Plans;

public sealed class PlanCatalogService(NexoraDbContext db, IAuditLogWriter audit) : IPlanCatalogService
{
    public async Task<IReadOnlyList<FeatureView>> GetFeaturesAsync(CancellationToken ct) => await db.Features.OrderBy(x=>x.Code).Select(x=>new FeatureView(x.Id,x.Code,x.Name,x.IsActive)).ToListAsync(ct);
    public async Task<FeatureView> CreateFeatureAsync(string code,string name,CancellationToken ct) { var c=Code(code); var n=Name(name); if(await db.Features.AnyAsync(x=>x.Code==c,ct)) throw new PlanCatalogConflictException("Feature code already exists."); var x=new Feature(c,n,DateTimeOffset.UtcNow); db.Features.Add(x); await db.SaveChangesAsync(ct); return new(x.Id,x.Code,x.Name,x.IsActive); }
    public async Task<FeatureView?> UpdateFeatureAsync(Guid id,string name,bool active,CancellationToken ct) { var x=await db.Features.FindAsync([id],ct); if(x is null)return null; x.Update(Name(name),active); await db.SaveChangesAsync(ct); return new(x.Id,x.Code,x.Name,x.IsActive); }
    public async Task<IReadOnlyList<PlanView>> GetPlansAsync(CancellationToken ct) => await db.Plans.Include(x=>x.Features).ThenInclude(x=>x.Feature).OrderBy(x=>x.Code).Select(x=>new PlanView(x.Id,x.Code,x.Name,x.IsActive,x.IsPublic,x.IsTrialEligible,x.Features.Select(f=>new PlanFeatureView(f.FeatureId,f.Feature.Code,f.Enabled,f.Limit)).ToList())).ToListAsync(ct);
    public async Task<PlanView> CreatePlanAsync(string code,string name,CancellationToken ct) { var c=Code(code); var n=Name(name); if(await db.Plans.AnyAsync(x=>x.Code==c,ct)) throw new PlanCatalogConflictException("Plan code already exists."); var x=new Plan(c,n,DateTimeOffset.UtcNow); db.Plans.Add(x); await db.SaveChangesAsync(ct); return new(x.Id,x.Code,x.Name,x.IsActive,x.IsPublic,x.IsTrialEligible,[]); }
    public async Task<PlanView?> UpdatePlanAsync(Guid id,string name,bool active,bool isPublic,bool isTrialEligible,CancellationToken ct) { var x=await db.Plans.Include(p=>p.Features).ThenInclude(f=>f.Feature).SingleOrDefaultAsync(p=>p.Id==id,ct); if(x is null)return null; x.Update(Name(name),active); x.ConfigureCommercialAvailability(isPublic,isTrialEligible); await db.SaveChangesAsync(ct); return Map(x); }
    public async Task<PlanFeatureView?> ConfigurePlanFeatureAsync(Guid actorUserId,Guid planId,Guid featureId,bool enabled,int? limit,string correlationId,CancellationToken ct) { Limit(limit); var plan=await db.Plans.Include(x=>x.Features).SingleOrDefaultAsync(x=>x.Id==planId,ct); var feature=await db.Features.FindAsync([featureId],ct); if(plan is null||feature is null)return null; var link=plan.Features.SingleOrDefault(x=>x.FeatureId==featureId); var (oldEnabled,oldLimit)=link is null?((bool?)null,(int?)null):((bool?)link.Enabled,link.Limit); if(link is null){link=new(planId,featureId,enabled,limit);plan.Features.Add(link);}else link.Configure(enabled,limit); audit.Record(actorUserId,AuditActions.PlanFeatureConfigured,"PlanFeature",$"{planId}:{featureId}",correlationId,tenantId:null,new{planId,featureCode=feature.Code,oldEnabled,newEnabled=enabled,oldLimit,newLimit=limit}); await db.SaveChangesAsync(ct); return new(featureId,feature.Code,enabled,limit); }
    public async Task<IReadOnlyList<OverrideView>> GetOverridesAsync(Guid tenantId,CancellationToken ct)=>await db.TenantFeatureOverrides.Where(x=>x.TenantId==tenantId).Include(x=>x.Feature).Select(x=>new OverrideView(x.Id,x.TenantId,x.FeatureId,x.Feature.Code,x.Enabled,x.Limit)).ToListAsync(ct);
    public async Task<OverrideView?> ConfigureOverrideAsync(Guid actorUserId,Guid tenantId,Guid featureId,bool enabled,int? limit,string correlationId,CancellationToken ct){Limit(limit);if(!await db.Tenants.AnyAsync(x=>x.Id==tenantId,ct))return null;var feature=await db.Features.FindAsync([featureId],ct);if(feature is null)return null;var x=await db.TenantFeatureOverrides.SingleOrDefaultAsync(o=>o.TenantId==tenantId&&o.FeatureId==featureId,ct);var (oldEnabled,oldLimit)=x is null?((bool?)null,(int?)null):((bool?)x.Enabled,x.Limit);if(x is null){x=new(tenantId,featureId,enabled,limit);db.TenantFeatureOverrides.Add(x);}else x.Configure(enabled,limit);audit.Record(actorUserId,AuditActions.TenantFeatureOverrideConfigured,"TenantFeatureOverride",$"{tenantId}:{featureId}",correlationId,tenantId,new{featureCode=feature.Code,oldEnabled,newEnabled=enabled,oldLimit,newLimit=limit});await db.SaveChangesAsync(ct);return new(x.Id,x.TenantId,x.FeatureId,feature.Code,x.Enabled,x.Limit);}
    private static string Code(string value){var x=value.Trim().ToUpperInvariant();if(x.Length is <2 or >80)throw new PlanCatalogValidationException("Code is invalid.");return x;} private static string Name(string value){var x=value.Trim();if(x.Length is <2 or >120)throw new PlanCatalogValidationException("Name is invalid.");return x;} private static void Limit(int? value){if(value<0)throw new PlanCatalogValidationException("Limit cannot be negative.");} private static PlanView Map(Plan x)=>new(x.Id,x.Code,x.Name,x.IsActive,x.IsPublic,x.IsTrialEligible,x.Features.Select(f=>new PlanFeatureView(f.FeatureId,f.Feature.Code,f.Enabled,f.Limit)).ToList());
}
