using Microsoft.EntityFrameworkCore;using Nexora.Application.Customers;using Nexora.Domain.Customers;using Nexora.Infrastructure.Persistence;
namespace Nexora.Infrastructure.Customers;
public sealed class CustomerService(NexoraDbContext db,TimeProvider time):ICustomerService
{
 public async Task<CustomerPage>SearchAsync(Guid tenantId,string? search,string? status,string sort,int page,int pageSize,CancellationToken ct){page=Math.Max(1,page);pageSize=Math.Clamp(pageSize,1,100);var q=db.Customers.Where(x=>x.TenantId==tenantId);if(!string.IsNullOrWhiteSpace(search)){var s=search.Trim();q=db.Database.ProviderName=="Microsoft.EntityFrameworkCore.InMemory"?q.Where(x=>x.Name.Contains(s,StringComparison.OrdinalIgnoreCase)||(x.Email!=null&&x.Email.Contains(s,StringComparison.OrdinalIgnoreCase))||(x.Phone!=null&&x.Phone.Contains(s,StringComparison.OrdinalIgnoreCase))):q.Where(x=>EF.Functions.ILike(x.Name,$"%{s}%")||(x.Email!=null&&EF.Functions.ILike(x.Email,$"%{s}%"))||(x.Phone!=null&&EF.Functions.ILike(x.Phone,$"%{s}%")));}if(!string.IsNullOrWhiteSpace(status))q=q.Where(x=>x.Status==status);q=sort switch{"name_desc"=>q.OrderByDescending(x=>x.Name),"created"=>q.OrderBy(x=>x.CreatedAt),"created_desc"=>q.OrderByDescending(x=>x.CreatedAt),_=>q.OrderBy(x=>x.Name)};var total=await q.CountAsync(ct);var entities=await q.Skip((page-1)*pageSize).Take(pageSize).AsNoTracking().ToListAsync(ct);return new(entities.Select(Map).ToList(),page,pageSize,total);}
 public async Task<CustomerView?>GetAsync(Guid t,Guid id,CancellationToken ct){var x=await db.Customers.AsNoTracking().SingleOrDefaultAsync(x=>x.TenantId==t&&x.Id==id,ct);return x is null?null:Map(x);}
 public async Task<CustomerView>CreateAsync(Guid t,CustomerInput i,CancellationToken ct){Validate(i);var x=new Customer(t,i.Name.Trim(),Clean(i.Phone),Clean(i.Email),i.BirthDate,Clean(i.Notes),time.GetUtcNow());db.Customers.Add(x);await db.SaveChangesAsync(ct);return Map(x);}
 public async Task<CustomerView?>UpdateAsync(Guid t,Guid id,CustomerInput i,CancellationToken ct){Validate(i);var x=await db.Customers.SingleOrDefaultAsync(x=>x.TenantId==t&&x.Id==id,ct);if(x is null)return null;x.Update(i.Name.Trim(),Clean(i.Phone),Clean(i.Email),i.BirthDate,Clean(i.Notes),time.GetUtcNow());await db.SaveChangesAsync(ct);return Map(x);}
 public async Task<bool>DeleteAsync(Guid t,Guid id,CancellationToken ct){var x=await db.Customers.SingleOrDefaultAsync(x=>x.TenantId==t&&x.Id==id,ct);if(x is null)return false;db.Remove(x);await db.SaveChangesAsync(ct);return true;}
 private static void Validate(CustomerInput i){if(string.IsNullOrWhiteSpace(i.Name)||i.Name.Trim().Length>200)throw new CustomerValidationException("Customer name is invalid.");if(i.Email?.Length>320||i.Phone?.Length>40||i.Notes?.Length>4000)throw new CustomerValidationException("Customer data is invalid.");}
 private static string?Clean(string?v)=>string.IsNullOrWhiteSpace(v)?null:v.Trim();private static CustomerView Map(Customer x)=>new(x.Id,x.Name,x.Phone,x.Email,x.BirthDate,x.Notes,x.Status,x.CreatedAt,x.UpdatedAt);
}
