using System.Net;
using System.Net.Http.Json;
using System.Security.Cryptography;
using System.Text;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Nexora.Application.Administration;
using Nexora.Application.Billing;
using Nexora.Domain.Billing;
using Nexora.Domain.Identity;
using Nexora.Domain.Plans;
using Nexora.Infrastructure.Persistence;
using Nexora.Infrastructure.Billing;
using Microsoft.Extensions.Options;

namespace Nexora.IntegrationTests;
public sealed class BillingPaymentTests
{
 [Fact]public void WebhookSignatureRequiresARecentAuthenticTimestamp(){var now=new DateTimeOffset(2026,9,1,12,0,0,TimeSpan.Zero);var validator=new MercadoPagoWebhookSignatureValidator(Options.Create(new MercadoPagoOptions{WebhookSecret="test-webhook-secret",WebhookTimestampToleranceSeconds=300}),new FixedTimeProvider(now));var request="freshness";var recent=now.AddMinutes(-4).ToUnixTimeSeconds().ToString(System.Globalization.CultureInfo.InvariantCulture);var old=now.AddMinutes(-6).ToUnixTimeSeconds().ToString(System.Globalization.CultureInfo.InvariantCulture);var future=now.AddMinutes(6).ToUnixTimeSeconds().ToString(System.Globalization.CultureInfo.InvariantCulture);Assert.True(validator.Validate(Signature("payment",request,recent),request,"payment"));Assert.False(validator.Validate(Signature("payment",request,old),request,"payment"));Assert.False(validator.Validate(Signature("payment",request,future),request,"payment"));Assert.False(validator.Validate($"ts={recent},v1={new string('0',64)}",request,"payment"));}
 [Fact]public async Task CheckoutUsesInternalPriceIsTenantScopedAndWebhookIsAuthenticatedIdempotent()
 {
  await using var factory=new ApiFactory();var tenant=factory.CreateClient();var other=factory.CreateClient();var admin=factory.CreateClient();var token=await Register(tenant,"pay-tenant@nexora.test");var otherToken=await Register(other,"pay-other@nexora.test");await Register(admin,"pay-admin@nexora.test");var tenantId=await CreateTenant(tenant,token,"pay-tenant");_=await CreateTenant(other,otherToken,"pay-other");Guid planId;Guid subscriptionId;await using(var scope=factory.Services.CreateAsyncScope()){var db=scope.ServiceProvider.GetRequiredService<NexoraDbContext>();var now=DateTimeOffset.UtcNow;var plan=new Plan("PAY","Pay",now);var sub=new Subscription(tenantId,plan.Id,BillingInterval.Monthly,now,TimeSpan.FromDays(14));db.AddRange(plan,sub);await db.SaveChangesAsync();planId=plan.Id;subscriptionId=sub.Id;}await Promote(factory,"PAY-ADMIN@NEXORA.TEST");var adminToken=await Login(admin,"pay-admin@nexora.test");admin.DefaultRequestHeaders.Authorization=new("Bearer",adminToken);
  var monthly=await admin.PostAsJsonAsync("/api/v1/admin/billing/prices",new{planId,billingInterval="Monthly",currency="BRL",amount=99.90m});Assert.Equal(HttpStatusCode.Created,monthly.StatusCode);Assert.Equal(HttpStatusCode.Created,(await admin.PostAsJsonAsync("/api/v1/admin/billing/prices",new{planId,billingInterval="Yearly",currency="BRL",amount=999m})).StatusCode);Assert.Equal(HttpStatusCode.BadRequest,(await admin.PostAsJsonAsync("/api/v1/admin/billing/prices",new{planId,billingInterval="Yearly",currency="USD",amount=999m})).StatusCode);Assert.Equal(HttpStatusCode.Forbidden,(await tenant.PostAsJsonAsync("/api/v1/admin/billing/prices",new{planId,billingInterval="Yearly",currency="BRL",amount=999m})).StatusCode);
  var scoped=await Select(tenant,token,"pay-tenant");tenant.DefaultRequestHeaders.Authorization=new("Bearer",scoped);factory.PaymentGateway.CheckoutResult=new("mp-100",BillingPaymentStatus.Pending,"https://checkout.test/mp-100","safe-qr",DateTimeOffset.UtcNow);var checkout=await tenant.PostAsJsonAsync("/api/v1/billing/checkout",new{paymentMethod="Pix",payerEmail="payer@nexora.test",amount=0.01,currency="USD",tenantId=Guid.NewGuid()});Assert.Equal(HttpStatusCode.OK,checkout.StatusCode);var view=(await checkout.Content.ReadFromJsonAsync<System.Text.Json.JsonElement>());Assert.Equal(99.90m,view.GetProperty("amount").GetDecimal());Assert.Equal("BRL",view.GetProperty("currency").GetString());
  other.DefaultRequestHeaders.Authorization=new("Bearer",await Select(other,otherToken,"pay-other"));Assert.Empty((await other.GetFromJsonAsync<System.Text.Json.JsonElement[]>("/api/v1/billing/invoices"))!);Assert.Single((await tenant.GetFromJsonAsync<System.Text.Json.JsonElement[]>("/api/v1/billing/invoices"))!);
  var invalid=await tenant.PostAsJsonAsync("/api/v1/payments/webhooks/mercado-pago?data.id=mp-100",new{id=10,type="payment",action="payment.updated",data=new{id="mp-100"}});Assert.Equal(HttpStatusCode.Unauthorized,invalid.StatusCode);
  factory.PaymentGateway.PaymentResult=new("mp-100",BillingPaymentStatus.Approved,99.90m,"BRL",PaymentMethod.Pix,DateTimeOffset.UtcNow.AddMinutes(1));var requestId="request-1";var timestamp=DateTimeOffset.UtcNow.ToUnixTimeSeconds().ToString(System.Globalization.CultureInfo.InvariantCulture);var sig=Signature("mp-100",requestId,timestamp);var webhook=new HttpRequestMessage(HttpMethod.Post,"/api/v1/payments/webhooks/mercado-pago?data.id=mp-100"){Content=JsonContent.Create(new{id=10,type="payment",action="payment.updated",data=new{id="mp-100"}})};webhook.Headers.Add("x-request-id",requestId);webhook.Headers.Add("x-signature",sig);Assert.Equal(HttpStatusCode.OK,(await tenant.SendAsync(webhook)).StatusCode);var duplicate=new HttpRequestMessage(HttpMethod.Post,"/api/v1/payments/webhooks/mercado-pago?data.id=mp-100"){Content=JsonContent.Create(new{id=10,type="payment",action="payment.updated",data=new{id="mp-100"}})};duplicate.Headers.Add("x-request-id",requestId);duplicate.Headers.Add("x-signature",sig);Assert.Equal(HttpStatusCode.OK,(await tenant.SendAsync(duplicate)).StatusCode);
  await using(var scope=factory.Services.CreateAsyncScope()){var db=scope.ServiceProvider.GetRequiredService<NexoraDbContext>();var invoice=await db.BillingInvoices.SingleAsync();var subscription=await db.Subscriptions.SingleAsync(x=>x.Id==subscriptionId);Assert.Equal(InvoiceStatus.Paid,invoice.Status);Assert.Equal(subscription.TrialEndAt,invoice.CoverageStart);Assert.Equal(subscription.TrialEndAt.AddMonths(1),invoice.CoverageEnd);Assert.Equal(SubscriptionStatus.Trialing,subscription.Status);Assert.Single(await db.ProcessedWebhookEvents.ToArrayAsync());Assert.Single(await db.BillingPayments.ToArrayAsync());}
 }
 [Fact]public async Task TransientGatewayFailureReusesInvoiceAndRejectedPaymentMarksActivePastDue(){await using var factory=new ApiFactory();var user=factory.CreateClient();var token=await Register(user,"retry@nexora.test");var tenantId=await CreateTenant(user,token,"retry");await using(var scope=factory.Services.CreateAsyncScope()){var db=scope.ServiceProvider.GetRequiredService<NexoraDbContext>();var now=DateTimeOffset.UtcNow;var p=new Plan("RETRY","Retry",now);var s=new Subscription(tenantId,p.Id,BillingInterval.Monthly,now,TimeSpan.FromDays(14));s.Activate(now);db.AddRange(p,s,new PlanPrice(p.Id,BillingInterval.Monthly,"BRL",10,now));await db.SaveChangesAsync();}user.DefaultRequestHeaders.Authorization=new("Bearer",await Select(user,token,"retry"));factory.PaymentGateway.CreateException=new PaymentGatewayUnavailableException("transient");Assert.Equal(HttpStatusCode.ServiceUnavailable,(await user.PostAsJsonAsync("/api/v1/billing/checkout",new{paymentMethod="Pix",payerEmail="retry@nexora.test"})).StatusCode);factory.PaymentGateway.CreateException=null;factory.PaymentGateway.CheckoutResult=new("retry-payment",BillingPaymentStatus.Rejected,null,null,DateTimeOffset.UtcNow);Assert.Equal(HttpStatusCode.OK,(await user.PostAsJsonAsync("/api/v1/billing/checkout",new{paymentMethod="Pix",payerEmail="retry@nexora.test"})).StatusCode);await using var verify=factory.Services.CreateAsyncScope();var verifyDb=verify.ServiceProvider.GetRequiredService<NexoraDbContext>();Assert.Single(await verifyDb.BillingInvoices.ToArrayAsync());Assert.Equal(SubscriptionStatus.PastDue,(await verifyDb.Subscriptions.SingleAsync(x=>x.TenantId==tenantId)).Status);}
 private static string Signature(string data,string request,string ts){var manifest=$"id:{data};request-id:{request};ts:{ts};";var hash=HMACSHA256.HashData(Encoding.UTF8.GetBytes("test-webhook-secret"),Encoding.UTF8.GetBytes(manifest));return $"ts={ts},v1={Convert.ToHexString(hash).ToLowerInvariant()}";}
 private static async Task<string>Register(HttpClient c,string email){var r=await c.PostAsJsonAsync("/api/v1/identity/register",new{email,password="Correct-Horse-42"});r.EnsureSuccessStatusCode();Cookie(c,r);return(await r.Content.ReadFromJsonAsync<Token>())!.AccessToken;}private static async Task<string>Login(HttpClient c,string email){var r=await c.PostAsJsonAsync("/api/v1/identity/login",new{email,password="Correct-Horse-42"});r.EnsureSuccessStatusCode();Cookie(c,r);return(await r.Content.ReadFromJsonAsync<Token>())!.AccessToken;}private static async Task<Guid>CreateTenant(HttpClient c,string token,string slug){c.DefaultRequestHeaders.Authorization=new("Bearer",token);var r=await c.PostAsJsonAsync("/api/v1/tenants",new{name=slug,slug,timeZoneId="UTC"});r.EnsureSuccessStatusCode();return(await r.Content.ReadFromJsonAsync<TenantDto>())!.Id;}private static async Task<string>Select(HttpClient c,string token,string slug){c.DefaultRequestHeaders.Authorization=new("Bearer",token);var r=await c.PostAsJsonAsync($"/api/v1/t/{slug}/session",new{});r.EnsureSuccessStatusCode();c.DefaultRequestHeaders.Remove("Cookie");Cookie(c,r);return(await r.Content.ReadFromJsonAsync<Token>())!.AccessToken;}private static void Cookie(HttpClient c,HttpResponseMessage r){c.DefaultRequestHeaders.Remove("Cookie");c.DefaultRequestHeaders.Add("Cookie",r.Headers.GetValues("Set-Cookie").Single(x=>x.StartsWith("nexora_refresh=",StringComparison.Ordinal)).Split(';',2)[0]);}private static async Task Promote(ApiFactory f,string email){await using var s=f.Services.CreateAsyncScope();var db=s.ServiceProvider.GetRequiredService<NexoraDbContext>();var u=await db.Users.SingleAsync(x=>x.NormalizedEmail==email);var role=new Role("PlatformAdmin");var p=new Permission(PlatformPermissions.Access);role.Permissions.Add(new RolePermission(role.Id,p.Id));u.Roles.Add(new UserRole(u.Id,role.Id));db.AddRange(role,p);await db.SaveChangesAsync();}
 private sealed record Token(string AccessToken);private sealed record TenantDto(Guid Id);
 private sealed class FixedTimeProvider(DateTimeOffset now):TimeProvider{public override DateTimeOffset GetUtcNow()=>now;}
}
