using System.Net;using System.Net.Http.Headers;using System.Net.Http.Json;using Microsoft.EntityFrameworkCore;using Microsoft.Extensions.DependencyInjection;using Nexora.Application.Tenancy;using Nexora.Domain.Tenancy;using Nexora.Infrastructure.Persistence;
namespace Nexora.IntegrationTests;
public sealed class CustomerAuthorizationTests
{
 [Fact] public async Task PermissionsAreTenantScopedAndIdorIsHidden()
 {
  await using var f=new ApiFactory();var a=f.CreateClient();var b=f.CreateClient();var outsider=f.CreateClient();
  var aGlobal=await Register(a,"multi@nexora.test");var bGlobal=await Register(b,"ownerb@nexora.test");var outsiderToken=await Register(outsider,"outside@nexora.test");
  var ta=await CreateTenant(a,aGlobal,"tenant-a6");var tb=await CreateTenant(b,bGlobal,"tenant-b6");
  await using(var scope=f.Services.CreateAsyncScope()){var db=scope.ServiceProvider.GetRequiredService<NexoraDbContext>();var user=await db.Users.SingleAsync(x=>x.NormalizedEmail=="MULTI@NEXORA.TEST");var noAccess=new TenantRole(tb,"VIEWER","No customer access",false);db.TenantRoles.Add(noAccess);db.TenantUsers.Add(new TenantUser(tb,user.Id,noAccess.Id,DateTimeOffset.UtcNow));await db.SaveChangesAsync();}
  var tokenA=await Select(a,aGlobal,"tenant-a6");a.DefaultRequestHeaders.Authorization=new("Bearer",tokenA);
  var created=await a.PostAsJsonAsync("/api/v1/customers",new{name="Alice",phone="123",email="a@test.local",birthDate="1990-01-01",notes="A"});Assert.Equal(HttpStatusCode.Created,created.StatusCode);var customer=(await created.Content.ReadFromJsonAsync<CustomerDto>())!;
  var second=await a.PostAsJsonAsync("/api/v1/customers",new{name="Bruno",phone="456",email="b@test.local",birthDate=(string?)null,notes="B"});var secondCustomer=(await second.Content.ReadFromJsonAsync<CustomerDto>())!;var paged=await a.GetFromJsonAsync<PageDto>("/api/v1/customers?search=Bruno&page=1&pageSize=1");Assert.NotNull(paged);Assert.Single(paged.Items);Assert.Equal(2,(await a.GetFromJsonAsync<FullPageDto>("/api/v1/customers?page=1&pageSize=1"))!.Total);Assert.Equal(HttpStatusCode.OK,(await a.PutAsJsonAsync($"/api/v1/customers/{secondCustomer.Id}",new{name="Bruno Updated",phone="456",email="b@test.local",birthDate=(string?)null,notes="Updated"})).StatusCode);Assert.Equal(HttpStatusCode.NoContent,(await a.DeleteAsync($"/api/v1/customers/{secondCustomer.Id}")).StatusCode);Assert.Equal(HttpStatusCode.BadRequest,(await a.PostAsJsonAsync("/api/v1/customers",new{name="",phone="",email="",birthDate=(string?)null,notes=""})).StatusCode);
  var tokenB=await Select(a,aGlobal,"tenant-b6");a.DefaultRequestHeaders.Authorization=new("Bearer",tokenB);Assert.Equal(HttpStatusCode.Forbidden,(await a.GetAsync("/api/v1/customers")).StatusCode);Assert.Equal(HttpStatusCode.Forbidden,(await a.GetAsync($"/api/v1/customers/{customer.Id}")).StatusCode);
  outsider.DefaultRequestHeaders.Authorization=new("Bearer",outsiderToken);Assert.Equal(HttpStatusCode.Unauthorized,(await outsider.PostAsync("/api/v1/t/tenant-a6/session",null)).StatusCode);
  Assert.Equal(HttpStatusCode.Unauthorized,(await f.CreateClient().GetAsync("/api/v1/customers")).StatusCode);
  await using(var scope=f.Services.CreateAsyncScope()){var db=scope.ServiceProvider.GetRequiredService<NexoraDbContext>();var role=await db.TenantRoles.SingleAsync(x=>x.TenantId==tb&&x.Name=="VIEWER");role.Permissions.Add(new TenantRolePermission(role.Id,TenantPermissions.CustomersRead));await db.SaveChangesAsync();}
  var page=await a.GetFromJsonAsync<PageDto>("/api/v1/customers?page=1&pageSize=10");Assert.NotNull(page);Assert.Empty(page.Items);
 }
 [Fact]public async Task RoleFromAnotherTenantCannotBeAssigned(){await using var f=new ApiFactory();var c=f.CreateClient();var token=await Register(c,"roles@nexora.test");var a=await CreateTenant(c,token,"roles-a");var b=await CreateTenant(c,token,"roles-b");await using var scope=f.Services.CreateAsyncScope();var db=scope.ServiceProvider.GetRequiredService<NexoraDbContext>();var membership=await db.TenantUsers.SingleAsync(x=>x.TenantId==a);var role=await db.TenantRoles.SingleAsync(x=>x.TenantId==b);var service=scope.ServiceProvider.GetRequiredService<ITenancyService>();Assert.False(await service.AssignRoleAsync(a,membership.Id,role.Id,CancellationToken.None));}
 private static async Task<string>Register(HttpClient c,string email){var r=await c.PostAsJsonAsync("/api/v1/identity/register",new{email,password="Correct-Horse-42"});r.EnsureSuccessStatusCode();SetCookie(c,r);return(await r.Content.ReadFromJsonAsync<TokenDto>())!.AccessToken;}
 private static async Task<Guid>CreateTenant(HttpClient c,string token,string slug){c.DefaultRequestHeaders.Authorization=new("Bearer",token);var r=await c.PostAsJsonAsync("/api/v1/tenants",new{name=slug,slug,timeZoneId="UTC"});r.EnsureSuccessStatusCode();return(await r.Content.ReadFromJsonAsync<TenantDto>())!.Id;}
 private static async Task<string>Select(HttpClient c,string token,string slug){c.DefaultRequestHeaders.Authorization=new("Bearer",token);var r=await c.PostAsJsonAsync($"/api/v1/t/{slug}/session",new{});r.EnsureSuccessStatusCode();c.DefaultRequestHeaders.Remove("Cookie");SetCookie(c,r);return(await r.Content.ReadFromJsonAsync<TokenDto>())!.AccessToken;}
 private static void SetCookie(HttpClient c,HttpResponseMessage r)=>c.DefaultRequestHeaders.Add("Cookie",r.Headers.GetValues("Set-Cookie").Single(x=>x.StartsWith("nexora_refresh=",StringComparison.Ordinal)).Split(';',2)[0]);
 private sealed record TokenDto(string AccessToken);private sealed record TenantDto(Guid Id);private sealed record CustomerDto(Guid Id);private sealed record PageDto(CustomerDto[] Items);private sealed record FullPageDto(CustomerDto[] Items,int Total);
}
