using System.Net;
using System.Net.Http.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Nexora.Application.Administration;
using Nexora.Application.Plans;
using Nexora.Domain.Identity;
using Nexora.Domain.Plans;
using Nexora.Domain.Billing;
using Nexora.Domain.Tenancy;
using Nexora.Infrastructure.Persistence;

namespace Nexora.IntegrationTests;

public sealed class SubscriptionTests
{
    [Fact]
    public async Task PlatformLifecycleIsAuditedIsolatedAndDrivesPersistentPlanProvider()
    {
        await using var factory=ApiFactory.WithPersistentPlanProvider();var regular=factory.CreateClient();var other=factory.CreateClient();var admin=factory.CreateClient();
        var regularGlobal=await Register(regular,"billing-tenant@nexora.test");var otherGlobal=await Register(other,"billing-other@nexora.test");await Register(admin,"billing-admin@nexora.test");
        var tenantId=await CreateTenant(regular,regularGlobal,"billing-tenant");_=await CreateTenant(other,otherGlobal,"billing-other");
        Guid planA;Guid planB;Guid featureId;
        await using(var scope=factory.Services.CreateAsyncScope()){var db=scope.ServiceProvider.GetRequiredService<NexoraDbContext>();var now=DateTimeOffset.UtcNow;var a=new Plan("BASIC","Basic",now);var b=new Plan("PRO","Pro",now);var feature=new Feature("REPORTS","Reports",now);a.Features.Add(new PlanFeature(a.Id,feature.Id,false,1));b.Features.Add(new PlanFeature(b.Id,feature.Id,true,10));db.AddRange(a,b,feature);await db.SaveChangesAsync();planA=a.Id;planB=b.Id;featureId=feature.Id;}
        await Promote(factory,"BILLING-ADMIN@NEXORA.TEST");admin.DefaultRequestHeaders.Authorization=new("Bearer",await Login(admin,"billing-admin@nexora.test"));regular.DefaultRequestHeaders.Authorization=new("Bearer",regularGlobal);
        Assert.Equal(HttpStatusCode.Unauthorized,(await factory.CreateClient().GetAsync("/api/v1/admin/subscriptions")).StatusCode);Assert.Equal(HttpStatusCode.Forbidden,(await regular.GetAsync("/api/v1/admin/subscriptions")).StatusCode);
        var createdResponse=await admin.PostAsJsonAsync("/api/v1/admin/subscriptions",new{tenantId,planId=planA,billingInterval="Monthly"});Assert.Equal(HttpStatusCode.Created,createdResponse.StatusCode);var created=(await createdResponse.Content.ReadFromJsonAsync<SubscriptionDto>())!;Assert.Equal("Trialing",created.Status);Assert.Equal(14,(created.TrialEndAt-created.TrialStartAt).TotalDays);
        Assert.Equal(HttpStatusCode.Conflict,(await admin.PostAsJsonAsync("/api/v1/admin/subscriptions",new{tenantId,planId=planA,billingInterval="Yearly"})).StatusCode);
        await using(var scope=factory.Services.CreateAsyncScope()){var provider=scope.ServiceProvider.GetRequiredService<ITenantPlanProvider>();var features=scope.ServiceProvider.GetRequiredService<IFeatureAccessService>();Assert.Equal(planA,await provider.GetCurrentPlanIdAsync(tenantId,CancellationToken.None));Assert.Equal(new FeatureAccess(false,1),await features.ResolveAsync(tenantId,"REPORTS",CancellationToken.None));}
        var changed=await Post<SubscriptionDto>(admin,$"/api/v1/admin/subscriptions/{created.Id}/change-plan",new{planId=planB});Assert.Equal(planB,changed.PlanId);
        await using(var scope=factory.Services.CreateAsyncScope()){var provider=scope.ServiceProvider.GetRequiredService<ITenantPlanProvider>();var features=scope.ServiceProvider.GetRequiredService<IFeatureAccessService>();Assert.Equal(planB,await provider.GetCurrentPlanIdAsync(tenantId,CancellationToken.None));Assert.Equal(new FeatureAccess(true,10),await features.ResolveAsync(tenantId,"REPORTS",CancellationToken.None));}
        var active=await Post<SubscriptionDto>(admin,$"/api/v1/admin/subscriptions/{created.Id}/activate",new{});Assert.Equal("Active",active.Status);var pastDue=await Post<SubscriptionDto>(admin,$"/api/v1/admin/subscriptions/{created.Id}/mark-past-due",new{});Assert.Equal("PastDue",pastDue.Status);var regularized=await Post<SubscriptionDto>(admin,$"/api/v1/admin/subscriptions/{created.Id}/activate",new{});Assert.Equal("Active",regularized.Status);
        var canceled=await Post<SubscriptionDto>(admin,$"/api/v1/admin/subscriptions/{created.Id}/cancel-immediately",new{});Assert.Equal("Canceled",canceled.Status);Assert.Equal(HttpStatusCode.BadRequest,(await admin.PostAsJsonAsync($"/api/v1/admin/subscriptions/{created.Id}/mark-past-due",new{})).StatusCode);
        await using(var scope=factory.Services.CreateAsyncScope()){var provider=scope.ServiceProvider.GetRequiredService<ITenantPlanProvider>();Assert.Null(await provider.GetCurrentPlanIdAsync(tenantId,CancellationToken.None));var db=scope.ServiceProvider.GetRequiredService<NexoraDbContext>();Assert.True(await db.SubscriptionEvents.CountAsync(x=>x.SubscriptionId==created.Id)>=6);Assert.Contains(await db.AuditLogs.Where(x=>x.TargetId==created.Id.ToString()).Select(x=>x.Action).ToArrayAsync(),x=>x=="subscription.plan_changed");Assert.Equal(featureId,(await db.Features.SingleAsync(x=>x.Code=="REPORTS")).Id);}
        regular.DefaultRequestHeaders.Authorization=new("Bearer",await Select(regular,regularGlobal,"billing-tenant"));Assert.Equal(HttpStatusCode.OK,(await regular.GetAsync("/api/v1/subscription")).StatusCode);other.DefaultRequestHeaders.Authorization=new("Bearer",await Select(other,otherGlobal,"billing-other"));Assert.Equal(HttpStatusCode.NotFound,(await other.GetAsync("/api/v1/subscription")).StatusCode);
    }
    [Fact]public async Task ScheduledCancellationKeepsActiveEntitlement(){await using var factory=ApiFactory.WithPersistentPlanProvider();var regular=factory.CreateClient();var admin=factory.CreateClient();var global=await Register(regular,"billing-cancel@nexora.test");await Register(admin,"billing-cancel-admin@nexora.test");var tenant=await CreateTenant(regular,global,"billing-cancel");Guid plan;await using(var scope=factory.Services.CreateAsyncScope()){var db=scope.ServiceProvider.GetRequiredService<NexoraDbContext>();var p=new Plan("MONTHLY","Monthly",DateTimeOffset.UtcNow);db.Add(p);await db.SaveChangesAsync();plan=p.Id;}await Promote(factory,"BILLING-CANCEL-ADMIN@NEXORA.TEST");admin.DefaultRequestHeaders.Authorization=new("Bearer",await Login(admin,"billing-cancel-admin@nexora.test"));var created=await Post<SubscriptionDto>(admin,"/api/v1/admin/subscriptions",new{tenantId=tenant,planId=plan,billingInterval="Monthly"});_=await Post<SubscriptionDto>(admin,$"/api/v1/admin/subscriptions/{created.Id}/activate",new{});var scheduled=await Post<SubscriptionDto>(admin,$"/api/v1/admin/subscriptions/{created.Id}/cancel-at-period-end",new{});Assert.Equal("Active",scheduled.Status);Assert.True(scheduled.CancelAtPeriodEnd);await using var finalScope=factory.Services.CreateAsyncScope();Assert.Equal(plan,await finalScope.ServiceProvider.GetRequiredService<ITenantPlanProvider>().GetCurrentPlanIdAsync(tenant,CancellationToken.None));}
    [Fact]public async Task ProviderExpiresFinishedTrialAndPastDueAfterGraceButKeepsGraceEntitlement(){await using var factory=ApiFactory.WithPersistentPlanProvider();_=factory.CreateClient();Guid expiredTrialId;Guid expiredPastDueId;Guid graceTenantId;Guid planId;await using(var scope=factory.Services.CreateAsyncScope()){var db=scope.ServiceProvider.GetRequiredService<NexoraDbContext>();var now=DateTimeOffset.UtcNow;var plan=new Plan("LIFECYCLE","Lifecycle",now);var expiredTrialTenant=new Tenant("Expired trial","expired-trial","UTC",now);var expiredPastDueTenant=new Tenant("Expired due","expired-due","UTC",now);var graceTenant=new Tenant("Grace","grace","UTC",now);var expiredTrial=new Subscription(expiredTrialTenant.Id,plan.Id,BillingInterval.Monthly,now.AddDays(-20),TimeSpan.FromDays(14));var expiredDue=new Subscription(expiredPastDueTenant.Id,plan.Id,BillingInterval.Monthly,now.AddDays(-20),TimeSpan.FromDays(14));expiredDue.Activate(now.AddDays(-10));expiredDue.MarkPastDue(now.AddDays(-8));var grace=new Subscription(graceTenant.Id,plan.Id,BillingInterval.Monthly,now.AddDays(-20),TimeSpan.FromDays(14));grace.Activate(now.AddDays(-5));grace.MarkPastDue(now.AddDays(-3));db.AddRange(plan,expiredTrialTenant,expiredPastDueTenant,graceTenant,expiredTrial,expiredDue,grace);await db.SaveChangesAsync();expiredTrialId=expiredTrial.Id;expiredPastDueId=expiredDue.Id;graceTenantId=graceTenant.Id;planId=plan.Id;}await using(var scope=factory.Services.CreateAsyncScope()){var provider=scope.ServiceProvider.GetRequiredService<ITenantPlanProvider>();var db=scope.ServiceProvider.GetRequiredService<NexoraDbContext>();Assert.Null(await provider.GetCurrentPlanIdAsync((await db.Subscriptions.SingleAsync(x=>x.Id==expiredTrialId)).TenantId,CancellationToken.None));db.ChangeTracker.Clear();Assert.Null(await provider.GetCurrentPlanIdAsync((await db.Subscriptions.SingleAsync(x=>x.Id==expiredPastDueId)).TenantId,CancellationToken.None));db.ChangeTracker.Clear();Assert.Equal(planId,await provider.GetCurrentPlanIdAsync(graceTenantId,CancellationToken.None));Assert.Equal(2,await db.Subscriptions.CountAsync(x=>x.Status==SubscriptionStatus.Expired));}}
    private static async Task<T> Post<T>(HttpClient client,string uri,object body){var response=await client.PostAsJsonAsync(uri,body);if(!response.IsSuccessStatusCode)throw new HttpRequestException($"{(int)response.StatusCode}: {await response.Content.ReadAsStringAsync()}");return(await response.Content.ReadFromJsonAsync<T>())!;}
    private static async Task<string> Register(HttpClient client,string email){var response=await client.PostAsJsonAsync("/api/v1/identity/register",new{email,password="Correct-Horse-42"});response.EnsureSuccessStatusCode();SetCookie(client,response);return(await response.Content.ReadFromJsonAsync<TokenDto>())!.AccessToken;}
    private static async Task<string> Login(HttpClient client,string email){var response=await client.PostAsJsonAsync("/api/v1/identity/login",new{email,password="Correct-Horse-42"});response.EnsureSuccessStatusCode();SetCookie(client,response);return(await response.Content.ReadFromJsonAsync<TokenDto>())!.AccessToken;}
    private static async Task<Guid> CreateTenant(HttpClient client,string token,string slug){client.DefaultRequestHeaders.Authorization=new("Bearer",token);var response=await client.PostAsJsonAsync("/api/v1/tenants",new{name=slug,slug,timeZoneId="UTC"});response.EnsureSuccessStatusCode();return(await response.Content.ReadFromJsonAsync<TenantDto>())!.Id;}
    private static async Task<string> Select(HttpClient client,string token,string slug){client.DefaultRequestHeaders.Authorization=new("Bearer",token);var response=await client.PostAsJsonAsync($"/api/v1/t/{slug}/session",new{});response.EnsureSuccessStatusCode();client.DefaultRequestHeaders.Remove("Cookie");SetCookie(client,response);return(await response.Content.ReadFromJsonAsync<TokenDto>())!.AccessToken;}
    private static async Task Promote(ApiFactory factory,string email){await using var scope=factory.Services.CreateAsyncScope();var db=scope.ServiceProvider.GetRequiredService<NexoraDbContext>();var user=await db.Users.SingleAsync(x=>x.NormalizedEmail==email);var role=new Role("PlatformAdmin");var permission=new Permission(PlatformPermissions.Access);role.Permissions.Add(new RolePermission(role.Id,permission.Id));user.Roles.Add(new UserRole(user.Id,role.Id));db.AddRange(role,permission);await db.SaveChangesAsync();}
    private static void SetCookie(HttpClient client,HttpResponseMessage response)=>client.DefaultRequestHeaders.Add("Cookie",response.Headers.GetValues("Set-Cookie").Single(x=>x.StartsWith("nexora_refresh=",StringComparison.Ordinal)).Split(';',2)[0]);
    private sealed record TokenDto(string AccessToken);private sealed record TenantDto(Guid Id);private sealed record SubscriptionDto(Guid Id,Guid PlanId,string Status,DateTimeOffset TrialStartAt,DateTimeOffset TrialEndAt,bool CancelAtPeriodEnd);
}
