import { Component, computed, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { HttpClient } from '@angular/common/http';
import { APP_CONFIG } from '../../core/config/app-config';
import { CommonModule } from '@angular/common';

interface Appointment { id:string;customerId:string;professionalId:string;serviceId:string;startAtLocal:string;endAtLocal:string;status:string;notes?:string }
interface ScheduleContext { timeZoneId:string }

@Component({selector:'app-schedule-page',imports:[FormsModule,CommonModule],template:`
<main><header><div><span>Agenda</span><h1>Agenda do tenant</h1><small>Timezone oficial: {{timeZoneId()||'carregando...'}}</small></div><nav><button (click)="setMode('day')" [class.active]="mode()==='day'">Dia</button><button (click)="setMode('week')" [class.active]="mode()==='week'">Semana</button></nav></header>
<section class="filters"><input type="date" [(ngModel)]="selectedDate" (change)="load()"><button (click)="editing.set(true)">Novo agendamento</button><button (click)="showHours.set(!showHours())">Disponibilidade</button><button (click)="showBlock.set(!showBlock())">Bloqueio</button></section>
@if(editing()){<form (ngSubmit)="saveAppointment()"><h2>{{form.id?'Editar':'Novo'}} agendamento</h2><input [(ngModel)]="form.customerId" name="customer" required placeholder="ID do cliente"><input [(ngModel)]="form.professionalId" name="professional" required placeholder="ID do profissional"><input [(ngModel)]="form.serviceId" name="service" required placeholder="ID do serviço"><input [(ngModel)]="form.startAt" name="start" required placeholder="2026-09-15T14:00:00-03:00"><textarea [(ngModel)]="form.notes" name="notes" placeholder="Observações"></textarea><div><button>Salvar</button><button type="button" (click)="closeForm()">Cancelar</button></div><p>Informe offset explícito. A API valida o horário contra {{timeZoneId()}}.</p></form>}
@if(showHours()){<form (ngSubmit)="saveHours()"><h2>Horário recorrente local</h2><input [(ngModel)]="hours.professionalId" name="hp" required placeholder="ID do profissional"><select [(ngModel)]="hours.dayOfWeek" name="day"><option *ngFor="let d of days" [value]="d.value">{{d.label}}</option></select><input type="time" [(ngModel)]="hours.startLocal" name="hs" required><input type="time" [(ngModel)]="hours.endLocal" name="he" required><button>Salvar disponibilidade</button></form>}
@if(showBlock()){<form (ngSubmit)="saveBlock()"><h2>Bloquear agenda</h2><input [(ngModel)]="block.professionalId" name="bp" required placeholder="ID do profissional"><input [(ngModel)]="block.startAt" name="bs" required placeholder="Início com offset"><input [(ngModel)]="block.endAt" name="be" required placeholder="Fim com offset"><input [(ngModel)]="block.reason" name="br" placeholder="Motivo"><button>Criar bloqueio</button></form>}
<section class="grid" [class.week]="mode()==='week'">@for(item of visible();track item.id){<article><time>{{item.startAtLocal | slice:0:16}}–{{item.endAtLocal | slice:11:16}}</time><b>{{item.status}}</b><small>Profissional {{item.professionalId}}</small><p>{{item.notes}}</p><footer><button (click)="edit(item)">Editar</button><button (click)="status(item,'Confirmed')">Confirmar</button><button (click)="cancel(item)">Cancelar</button></footer></article>}@empty{<p class="empty">Nenhum agendamento no período.</p>}</section>
@if(error()){<aside class="error">{{error()}}</aside>}</main>`,styles:[`:host{display:block;min-height:100vh;background:#f4f7fb;color:#17233c}main{max-width:1100px;margin:auto;padding:1.5rem}header,.filters,header nav,form div,footer{display:flex;gap:.7rem;align-items:center}header{justify-content:space-between}h1{margin:.2rem 0}button,input,select,textarea{padding:.7rem;border:1px solid #cbd5e1;border-radius:.5rem}button{cursor:pointer}.active,button:first-child{background:#1d4ed8;color:white}.filters{margin:1.5rem 0;flex-wrap:wrap}form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.7rem;background:white;padding:1rem;border-radius:.8rem;margin-bottom:1rem}form h2,form p,form textarea,form div{grid-column:1/-1}.grid{display:grid;grid-template-columns:1fr;gap:.7rem}.grid.week{grid-template-columns:repeat(2,minmax(0,1fr))}article{background:white;padding:1rem;border-left:4px solid #2563eb;border-radius:.7rem;display:grid;gap:.4rem}.error{position:fixed;right:1rem;bottom:1rem;background:#991b1b;color:white;padding:1rem;border-radius:.5rem}.empty{padding:2rem;background:white}@media(max-width:700px){header{align-items:flex-start;flex-direction:column}.grid.week,form{grid-template-columns:1fr}form>*{grid-column:1!important}footer{flex-wrap:wrap}}`]})
export class SchedulePage{
 private http=inject(HttpClient);private config=inject(APP_CONFIG);appointments=signal<Appointment[]>([]);timeZoneId=signal('');mode=signal<'day'|'week'>('day');editing=signal(false);showHours=signal(false);showBlock=signal(false);error=signal('');selectedDate=new Date().toISOString().slice(0,10);form:any={};hours:any={dayOfWeek:'Monday',startLocal:'09:00',endLocal:'18:00'};block:any={};days=[['Sunday','Domingo'],['Monday','Segunda'],['Tuesday','Terça'],['Wednesday','Quarta'],['Thursday','Quinta'],['Friday','Sexta'],['Saturday','Sábado']].map(([value,label])=>({value,label}));
 visible=computed(()=>{const end=new Date(`${this.selectedDate}T00:00:00Z`);end.setUTCDate(end.getUTCDate()+(this.mode()==='week'?7:1));const endDate=end.toISOString().slice(0,10);return this.appointments().filter(x=>x.startAtLocal.slice(0,10)>=this.selectedDate&&x.startAtLocal.slice(0,10)<endDate)});constructor(){this.http.get<ScheduleContext>(`${this.config.apiBaseUrl}/scheduling/context`).subscribe(x=>this.timeZoneId.set(x.timeZoneId));this.load()}
 setMode(value:'day'|'week'){this.mode.set(value);this.load()}load(){const start=new Date(`${this.selectedDate}T00:00:00Z`);start.setUTCDate(start.getUTCDate()-1);const end=new Date(`${this.selectedDate}T00:00:00Z`);end.setUTCDate(end.getUTCDate()+(this.mode()==='week'?8:2));this.http.get<Appointment[]>(`${this.config.apiBaseUrl}/appointments`,{params:{from:start.toISOString(),to:end.toISOString()}}).subscribe({next:x=>this.appointments.set(x),error:e=>this.fail(e)})}
 saveAppointment(){const body={customerId:this.form.customerId,professionalId:this.form.professionalId,serviceId:this.form.serviceId,startAt:this.form.startAt,notes:this.form.notes};const request=this.form.id?this.http.put(`${this.config.apiBaseUrl}/appointments/${this.form.id}`,body):this.http.post(`${this.config.apiBaseUrl}/appointments`,body);request.subscribe({next:()=>{this.closeForm();this.load()},error:e=>this.fail(e)})}
 saveHours(){this.http.put(`${this.config.apiBaseUrl}/working-hours`,{...this.hours,startLocal:`${this.hours.startLocal}:00`,endLocal:`${this.hours.endLocal}:00`}).subscribe({next:()=>this.showHours.set(false),error:e=>this.fail(e)})}
 saveBlock(){this.http.post(`${this.config.apiBaseUrl}/blocked-periods`,this.block).subscribe({next:()=>{this.showBlock.set(false);this.block={}},error:e=>this.fail(e)})}
 edit(x:Appointment){this.form={...x,startAt:x.startAtLocal};this.editing.set(true)}status(x:Appointment,status:string){this.http.patch(`${this.config.apiBaseUrl}/appointments/${x.id}/status`,{status}).subscribe({next:()=>this.load(),error:e=>this.fail(e)})}cancel(x:Appointment){this.http.patch(`${this.config.apiBaseUrl}/appointments/${x.id}/cancel`,{}).subscribe({next:()=>this.load(),error:e=>this.fail(e)})}closeForm(){this.editing.set(false);this.form={}}private fail(e:any){this.error.set(e?.error?.title||'Não foi possível concluir a operação.');setTimeout(()=>this.error.set(''),4000)}
}
